// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kJ6nGwTdUNKk7K3MbGVrQ3GzyX2V_PI',
    appId: '1:608035634413:web:468591787adf7f060020e4',
    messagingSenderId: '608035634413',
    projectId: 'inventory-master-b27c1',
    authDomain: 'inventory-master-b27c1.firebaseapp.com',
    storageBucket: 'inventory-master-b27c1.appspot.com',
    measurementId: 'G-MT3D6LV963',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XRngOrd9EVPcIaDfGmlYWRpByM7giqk',
    appId: '1:608035634413:android:a9edf7a04df2b0630020e4',
    messagingSenderId: '608035634413',
    projectId: 'inventory-master-b27c1',
    storageBucket: 'inventory-master-b27c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8EnPZzHIIxFVg8cIPpE5G6SBfjO7Ysdw',
    appId: '1:608035634413:ios:11dd6e0eb78a19900020e4',
    messagingSenderId: '608035634413',
    projectId: 'inventory-master-b27c1',
    storageBucket: 'inventory-master-b27c1.appspot.com',
    iosClientId: '608035634413-mp6nf1433tavuced6r2qoo6itlqm8guf.apps.googleusercontent.com',
    iosBundleId: 'com.example.productInventory',
  );
}
